
name := ExtGenerator
G4TARGET := $(name)
G4EXLIB := true

.PHONY: all
all: bin lib

include $(G4INSTALL)/config/architecture.gmk
#include $(G4INSTALL)/config/common.gmk
include $(G4INSTALL)/config/binmake.gmk
