# vim: ft=python :
import os
import os.path

import pprint
env = Environment()
print dir(env)
pprint.pprint( env.__dict__ )

libs = Split("boost_python")

print libs

Program('hello.c', 
        LIBS=['world'], 
        LIBPATH=".", 
        RPATH=Literal(os.path.join('\\$$ORIGIN', '.'))
        )
SharedLibrary('world', ['world.c'])
