import os

dirs = ["prog", "lib"]

env = Environment()

env.Append(CPPPATH=['#%s'%d for d in dirs])
env.Append(LIBPATH=["#install"])

Export("env")

for sub_dir in dirs:
    products = SConscript( '%s/SConscript'%sub_dir
                , variant_dir = 'build' + os.sep + sub_dir
                , duplicate = 0
                )
    env.Install('#install', products)
