import os
import os.path
Import('env')

prog = env.Program('prog',
            ['hello.c'], 
            LIBS=['world'],
            RPATH=Literal(os.path.join('\\$$ORIGIN'))
            )
Return('prog')
